name: AutoMessage
author: zAryon
description: A simple automessage plugin
version: 1.1
main: me.ianguuima.AutoMessage
commands:
  automessage:
    description: Main command, you'll use it for everything.
    aliases:
      - am
      - amsg
      - automsg